### ISSUE TITLE
Hi Dev Help me pls

### ISSUE THREAD

**Issue by axen1** [ismadevjs/Youtube-Views#1]
& C:/Users/bahad/AppData/Local/Programs/Python/Python311/python.exe c:/Users/bahad/OneDrive/Masaüstü/Youtube-Views-main/run.py
You're using Windows.
Performing system check...
###########################

NordVPN installation check: ✓
NordVPN service check: ✓
Opening NordVPN app and disconnecting if necessary...
NordVPN app launched: ✓
#####################################

You've entered a list of connection options. Checking list...

Done!

Your current ip-address is: 109.228.200.205

Connecting you to Estonia ...

your new ip-address is: 85.190.239.147

Done! Enjoy your new server.

DevTools listening on ws://127.0.0.1:52768/devtools/browser/4e204358-fa84-42c5-a873-c561b4d338a7
Created TensorFlow Lite XNNPACK delegate for CPU.
somthing wrong ...
restart ...

DevTools listening on ws://127.0.0.1:52850/devtools/browser/fa409e53-1886-4de1-9951-254edb14992f
Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "c:\Users\bahad\OneDrive\Masaüstü\Youtube-Views-main\run.py", line 400, in <module>
    run_it()
  File "c:\Users\bahad\OneDrive\Masaüstü\Youtube-Views-main\run.py", line 236, in run_it
    profile = WebDriverWait(browser, 20).until(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\bahad\OneDrive\Masaüstü\Youtube-Views-main\run.py", line 405, in <module>
    run_it()
  File "c:\Users\bahad\OneDrive\Masaüstü\Youtube-Views-main\run.py", line 236, in run_it
    profile = WebDriverWait(browser, 20).until(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by ismadevjs** [comment]
Hey there contact me on WhatsApp:
‪+974 5544 6537‬
